### ISSUE TITLE
Sioux City collaboration

### ISSUE THREAD

**Issue by sgdavis1** [bioneos/plant-hydration-monitor#3]
The Career Academy in Sioux City will be collaborating on this project as a part of the Iowa Clearinghouse work. There fork of the efforts is here: 

https://github.com/Ms-Johnson1-Sioux-City-Career-Academy/plant-hydration-monitor

**Comment by sgdavis1** [comment]
**Current Progress:**
* Hardware is ordered
* Repo is forked, and permissions are set
* Code exploration is initiated and ongoing 

**Next goals:**
* Execution of the web app locally on school laptops
* Successful flash of Sensor Reading code to embedded controllers

**Future goals:**
* Recording readings from controller to local web app

**Comment by garrett-lane** [comment]
hello world

**Comment by sgdavis1** [comment]
Hello @BlooperGMB and @garrett-lane !! This might help in your initial exploration of the ESP8266: https://www.instructables.com/Get-Started-with-ESP8266-Using-AT-Commands-NodeMCU/

I'd suggest you run the serial commands and make sure you can get it to talk to you before you first flash it. Also, I can confirm you don't need the USB-serial convertor, so you can just plugin the micro-usb cable and get started. Just remember to change the Arduino IDE port to the new serial port that is created. Good luck!
